---
      - name: Create  user 1
        user:
          name: "{{ item }}"
          password: $1$40gKCUMq$Cc0ggTrIwou1VpsWzwqUd/
          state: present
          shell: /bin/bash
          system: no
          createhome: yes
          home: /home/"{{ item }}"

        with_items:

            - sree1
            - sai1
            - pinky1
